'use client'
import { useEffect, useState } from 'react'
import { supabase } from '../../lib/supabase'
const fallbackImage='https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1200&q=85'
export default function Properties(){
 const [q,setQ]=useState(''),[tab,setTab]=useState('All'),[homes,setHomes]=useState<any[]>([]),[loading,setLoading]=useState(true)
 useEffect(()=>{const p=new URLSearchParams(window.location.search);setQ(p.get('search')||'');setTab(p.get('mode')==='Rent'?'For Rent':p.get('mode')==='Buy'?'For Sale':'All');(async()=>{const {data,error}=await supabase.from('listings').select('*').eq('kind','property').eq('status','active').eq('moderation_status','approved').order('created_at',{ascending:false});if(!error)setHomes(data||[]);setLoading(false)})()},[])
 const filtered=homes.filter(h=>{const text=`${h.title||''} ${h.city||''} ${h.state||''} ${h.zip_code||''}`.toLowerCase();const tag=h.property_mode==='rent'?'For Rent':'For Sale';return(!q||text.includes(q.toLowerCase()))&&(tab==='All'||tag===tab)})
 return <><nav className="nav container"><a className="brand" href="/"><span className="brandMark">H</span> havenly</a><div className="navLinks"><a href="/">Home</a><a href="/marketplace">Marketplace</a><a href="/policy">Safety</a></div><div className="navActions"><a href="/signin">Sign in</a><a className="btn btn-dark" href="/sell">List a property</a></div></nav><main className="container" style={{padding:'55px 0 100px'}}><span className="kicker">HOMES ACROSS THE USA</span><h1 style={{fontSize:'clamp(40px,6vw,64px)',letterSpacing:'-2.5px',margin:'10px 0'}}>Find a home that fits your life.</h1><p className="muted" style={{maxWidth:650,lineHeight:1.7}}>Browse approved homes available for sale or rent. Search by city, ZIP code or neighborhood.</p><div className="searchBox" style={{boxShadow:'none',border:'1px solid var(--line)',margin:'30px 0'}}><div className="searchInput"><span>⌕</span><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search city, ZIP code, neighborhood…"/><button onClick={()=>window.history.replaceState({},'',`/properties?search=${encodeURIComponent(q)}${tab!=='All'?`&mode=${tab==='For Rent'?'Rent':'Buy'}`:''}`)}>Search</button></div></div><div style={{display:'flex',gap:8,marginBottom:28}}>{['All','For Sale','For Rent'].map(x=><button key={x} onClick={()=>setTab(x)} className="btn" style={{background:tab===x?'var(--ink)':'white',color:tab===x?'white':'var(--ink)'}}>{x}</button>)}</div>{loading?<p className="muted">Loading approved homes…</p>:filtered.length?<div className="homeGrid">{filtered.map(h=><a href={`/listing/${h.id}`} className="homeCard" key={h.id}><div className="cardImage"><img src={h.images?.[0]||fallbackImage} alt={h.title}/><span className="pill">{h.property_mode==='rent'?'For Rent':'For Sale'}</span><span className="heart">♡</span></div><div className="cardBody"><div className="price">${Number(h.price).toLocaleString()}{h.property_mode==='rent'?'/mo':''}</div><h3>{h.title}</h3><p>{h.city}{h.state?`, ${h.state}`:''}</p><small>{h.beds??'—'} bd · {h.baths??'—'} ba · {h.sqft?Number(h.sqft).toLocaleString():'—'} sq ft</small></div></a>)}</div>:<div className="card" style={{padding:30}}><h3>No matching homes yet.</h3><p className="muted">Try another city, ZIP code or listing type, or check back as new approved listings are added.</p><a className="btn btn-dark" href="/sell">List a property</a></div>}</main></>
}
