'use client'
import { useEffect, useState } from 'react'
import { supabase } from '../../lib/supabase'

const fallback=[['Modern Lakeview Residence','Austin, TX','$845,000','4 bd · 3 ba · 2,680 sq ft','For Sale','https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1200&q=85'],['Sunlit Family Home','Irvine, CA','$3,450/mo','3 bd · 2 ba · 1,940 sq ft','For Rent','https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=1200&q=85'],['Contemporary City House','Dallas, TX','$629,000','3 bd · 2.5 ba · 2,210 sq ft','For Sale','https://images.unsplash.com/photo-1600566753086-00f18fb6b3ea?auto=format&fit=crop&w=1200&q=85'],['Desert Modern Retreat','Scottsdale, AZ','$1,180,000','4 bd · 4 ba · 3,120 sq ft','For Sale','https://images.unsplash.com/photo-1600607688969-a5bfcd646154?auto=format&fit=crop&w=1200&q=85']]

export default function Properties(){
 const[q,setQ]=useState(''); const[tab,setTab]=useState('All'); const[homes,setHomes]=useState<any[]>(fallback)
 useEffect(()=>{(async()=>{const {data}=await supabase.from('listings').select('*').eq('kind','property').eq('status','active').order('created_at',{ascending:false}); if(data?.length)setHomes(data)})() },[])
 const filtered=homes.filter(h=>{const text=Array.isArray(h)?h.join(' '):`${h.title} ${h.city} ${h.state||''}`; const tag=Array.isArray(h)?h[4]:(h.property_mode==='rent'?'For Rent':'For Sale'); return (!q||text.toLowerCase().includes(q.toLowerCase()))&&(tab==='All'||tag.toLowerCase().includes(tab.toLowerCase().replace('for ','')))})
 return <><nav className="nav container"><a className="brand" href="/"><span className="brandMark">H</span> havenly</a><div className="navLinks"><a href="/">Home</a><a href="/marketplace">Marketplace</a></div><div className="navActions"><a href="/signin">Sign in</a><a className="btn btn-dark" href="/sell">List a property</a></div></nav><main className="container" style={{padding:'55px 0 100px'}}><span className="kicker">HOMES ACROSS THE USA</span><h1 style={{fontSize:'48px',letterSpacing:'-2px',margin:'10px 0'}}>Find a home that fits your life.</h1><div className="searchBox" style={{boxShadow:'none',border:'1px solid var(--line)',margin:'30px 0'}}><div className="searchInput"><span>⌕</span><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search city, ZIP code, neighborhood…"/><button>Search</button></div></div><div style={{display:'flex',gap:8,marginBottom:28}}>{['All','For Sale','For Rent'].map(x=><button key={x} onClick={()=>setTab(x)} className="segmented button" style={{border:'1px solid var(--line)',borderRadius:8,padding:'10px 15px',background:tab===x?'var(--ink)':'white',color:tab===x?'white':'#555'}}>{x}</button>)}</div><div className="homeGrid">{filtered.map((h,i)=>{const a=Array.isArray(h); const title=a?h[0]:h.title, city=a?h[1]:`${h.city}${h.state?`, ${h.state}`:''}`, price=a?h[2]:`${h.currency||'USD'} ${Number(h.price).toLocaleString()}`, meta=a?h[3]:`${h.beds||'—'} bd · ${h.baths||'—'} ba · ${h.sqft?Number(h.sqft).toLocaleString():'—'} sq ft`, tag=a?h[4]:(h.property_mode==='rent'?'For Rent':'For Sale'), image=a?h[5]:(h.images?.[0]||fallback[0][5]); return <a href={!a && h.id ? `/listing/${h.id}` : '#'} className="homeCard" key={h.id||i}><div className="cardImage"><img src={image} alt=""/><span className="pill">{tag}</span><button className="heart">♡</button></div><div className="cardBody"><div className="price">{price}</div><h3>{title}</h3><p>{city}</p><small>{meta}</small></div></a>})}</div></main></>
}
