'use client'
import { useEffect, useState } from 'react'
import { supabase } from '../../lib/supabase'

export default function Dashboard(){
 const [user,setUser]=useState<any>(null),[listings,setListings]=useState<any[]>([]),[favorites,setFavorites]=useState<any[]>([]),[messages,setMessages]=useState<any[]>([])
 useEffect(()=>{(async()=>{const {data:{user}}=await supabase.auth.getUser();setUser(user);if(!user)return;const [l,f,m]=await Promise.all([supabase.from('listings').select('*').eq('seller_id',user.id).order('created_at',{ascending:false}),supabase.from('favorites').select('listing_id, listings(*)').eq('user_id',user.id),supabase.from('messages').select('*').or(`sender_id.eq.${user.id},receiver_id.eq.${user.id}`).order('created_at',{ascending:false})]);setListings(l.data||[]);setFavorites(f.data||[]);setMessages(m.data||[])})()},[])
 async function signOut(){await supabase.auth.signOut();location.href='/'}
 if(!user)return <main className="container" style={{padding:'70px 0'}}><h1>Sign in to view your dashboard.</h1><a className="btn btn-dark" href="/signin">Sign in</a></main>
 return <main><nav className="nav container"><a className="brand" href="/"><span className="brandMark">H</span> havenly</a><div className="navActions"><a href="/sell" className="btn btn-dark">+ Create listing</a><button className="btn" onClick={signOut}>Sign out</button></div></nav><section className="container" style={{padding:'50px 0 100px'}}><span className="kicker">YOUR HAVENLY</span><h1 style={{fontSize:46,letterSpacing:-2,margin:'8px 0 35px'}}>Dashboard</h1><div className="dashStats"><div><b>{listings.length}</b><span>Your listings</span></div><div><b>{favorites.length}</b><span>Saved listings</span></div><div><b>{messages.length}</b><span>Messages</span></div></div><div className="dashGrid"><section><h2>Your listings</h2>{listings.length?<div className="dashList">{listings.map(x=><a href={`/listing/${x.id}`} key={x.id}><b>{x.title}</b><span>${Number(x.price).toLocaleString()} · {x.city}</span><small>{x.status}</small></a>)}</div>:<p className="muted">You haven't listed anything yet. <a href="/sell">Create your first listing →</a></p>}</section><section><h2>Saved listings</h2>{favorites.length?<div className="dashList">{favorites.map(x=>x.listings&&<a href={`/listing/${x.listing_id}`} key={x.listing_id}><b>{x.listings.title}</b><span>${Number(x.listings.price).toLocaleString()} · {x.listings.city}</span></a>)}</div>:<p className="muted">Save homes and marketplace finds to see them here.</p>}</section><section><h2>Messages</h2>{messages.length?<div className="dashList">{messages.slice(0,8).map(x=><div key={x.id}><b>{x.sender_id===user.id?'You':'Seller / buyer'}</b><span>{x.body}</span><small>{new Date(x.created_at).toLocaleString()}</small></div>)}</div>:<p className="muted">Your buyer and seller conversations will appear here.</p>}</section></div></section></main>
}
